// <auto-generated />
using System;
using ASP_app.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASP_app.Migrations
{
  [DbContext(typeof(AppDbContext))]
  [Migration("20260124194137_Init_Blogs_Commnets")]
  partial class Init_Blogs_Commnets
  {
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
          .HasAnnotation("ProductVersion", "10.0.2")
          .HasAnnotation("Relational:MaxIdentifierLength", 128);

      SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

      modelBuilder.Entity("ASP_app.Models.Blog", b =>
          {
            b.Property<int>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("int");

            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

            b.Property<string>("Author")
                      .IsRequired()
                      .HasColumnType("nvarchar(max)");

            b.Property<string>("Content")
                      .IsRequired()
                      .HasColumnType("nvarchar(max)");

            b.Property<DateTime>("CreatedAt")
                      .HasColumnType("datetime2");

            b.Property<string>("Title")
                      .IsRequired()
                      .HasColumnType("nvarchar(max)");

            b.HasKey("Id");

            b.ToTable("Blogs");

            b.HasData(
                      new
                  {
                    Id = 1,
                    Author = "Quốc Mạnh Trần",
                    Content = "Chỉ tui đâu việc em nha. Hóa dép con tủ hết bè là tủ. Đâu chín gì đã áo khâu cửa yêu biển thế.",
                    CreatedAt = new DateTime(2026, 9, 15, 9, 0, 16, 706, DateTimeKind.Unspecified).AddTicks(5026),
                    Title = "Nha ờ nghỉ trăng lầu."
                  },
                      new
                  {
                    Id = 2,
                    Author = "Xuân Phương Phan",
                    Content = "Nón đỏ ừ. Khoan cửa tô bạn ghét. Độc đá bốn xanh. Vẽ áo hương đạp lầu độc.",
                    CreatedAt = new DateTime(2026, 8, 4, 9, 41, 59, 506, DateTimeKind.Unspecified).AddTicks(4469),
                    Title = "Ác bàn viết lỗi biết á."
                  },
                      new
                  {
                    Id = 3,
                    Author = "Duy Thành Phan",
                    Content = "Thích vàng đang. May quê làm nha đã đạp thế nghỉ. Ghế may mượn biển một quê á gì. Máy cái mướn mua đạp đập mua viết. Leo đã không bạn.",
                    CreatedAt = new DateTime(2026, 11, 10, 12, 6, 3, 103, DateTimeKind.Unspecified).AddTicks(9047),
                    Title = "Thuê thuê ừ bơi."
                  },
                      new
                  {
                    Id = 4,
                    Author = "Hương Tiên Phạm",
                    Content = "Sáu hết biển nón đã hương ghế làm xe mười. Thuê hàng trời mua mướn việc bàn. Nước ruộng á xe tôi giày viết mướn hết. Đâu quần tàu vá một. Cửa đồng sáu không tui ruộng leo tàu đỏ thích.",
                    CreatedAt = new DateTime(2026, 7, 30, 14, 36, 25, 147, DateTimeKind.Unspecified).AddTicks(4694),
                    Title = "Tô tám leo đạp hết tám thì khâu xuồng."
                  },
                      new
                  {
                    Id = 5,
                    Author = "Quang Sáng Hà",
                    Content = "Chết hóa không tám cái nha con thương xuồng. Một biết anh không quê gì may núi đập. Đập thích xuồng mượn chín hết xe. Mướn thích ừ gió tám mượn á hết mây đập. Vàng tàu xe bàn đã gió nón bảy ừ. Nước quần tàu ngọt nghỉ bàn đá nước.",
                    CreatedAt = new DateTime(2026, 11, 7, 16, 53, 6, 980, DateTimeKind.Unspecified).AddTicks(4352),
                    Title = "Nha giết bơi gì cái ừ hai làm thì."
                  },
                      new
                  {
                    Id = 6,
                    Author = "Ngọc Vy Hồ",
                    Content = "Đạp á con đá. Ruộng chìm làm thích tàu làm ba ba nước. Núi ngọt vá leo là đang phá. Trăng giết đã việc viết thuyền ruộng xuồng đang giết. Ba độc chín thuê núi viết đang khoan. Cửa tám khoảng thì việc.",
                    CreatedAt = new DateTime(2026, 10, 8, 17, 19, 19, 980, DateTimeKind.Unspecified).AddTicks(4736),
                    Title = "Dép cửa bảy trời cửa được nghỉ đang."
                  },
                      new
                  {
                    Id = 7,
                    Author = "Hiếu Phong Vương",
                    Content = "Bàn vàng nghỉ xanh khâu quần thì may được quần. Thế khâu tui anh đỏ tám hóa hương. Ruộng viết đá leo hương lầu ừ nhà tím trời. May ba kim nón. Ngọt xuồng may tủ đá chìm á thế đạp.",
                    CreatedAt = new DateTime(2026, 5, 30, 3, 24, 24, 817, DateTimeKind.Unspecified).AddTicks(7293),
                    Title = "Thì chết mướn mua á bạn cửa giết thương."
                  },
                      new
                  {
                    Id = 8,
                    Author = "Ðông Trà Phạm",
                    Content = "Tàu đỏ biết bàn được á. Chỉ là gió ừ thế lỗi khâu làm bảy tám. Ờ đánh á bè mười trăng anh chìm mua. Hai ngọt độc anh mượn lầu bè độc.",
                    CreatedAt = new DateTime(2026, 5, 24, 16, 20, 38, 833, DateTimeKind.Unspecified).AddTicks(8095),
                    Title = "Năm gì hóa thương mây nước."
                  },
                      new
                  {
                    Id = 9,
                    Author = "Thiện Tiên Vương",
                    Content = "Bơi thôi mười. Phá mượn không tui tui phá sáu viết ác ác. Một hết nước bạn sáu việc đá đang bè tô. Vẽ năm thuê đỏ á quần bàn.",
                    CreatedAt = new DateTime(2026, 11, 12, 14, 17, 15, 980, DateTimeKind.Unspecified).AddTicks(8595),
                    Title = "Thì khâu bốn bạn cái tám giày giày nón may."
                  },
                      new
                  {
                    Id = 10,
                    Author = "Anh Thái Tăng",
                    Content = "Nước ba nha. Mướn độc bè cái ghét chết. Giày ghét chín máy bạn con á chết anh sáu. Yêu tím biết được. Đâu yêu quần.",
                    CreatedAt = new DateTime(2026, 9, 24, 18, 58, 6, 721, DateTimeKind.Unspecified).AddTicks(8559),
                    Title = "Bè hai bốn ruộng."
                  });
          });

      modelBuilder.Entity("ASP_app.Models.Comment", b =>
          {
            b.Property<int>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("int");

            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

            b.Property<int>("BlogId")
                      .HasColumnType("int");

            b.Property<string>("Content")
                      .IsRequired()
                      .HasColumnType("nvarchar(max)");

            b.Property<int>("Rating")
                      .HasColumnType("int");

            b.Property<string>("User")
                      .IsRequired()
                      .HasColumnType("nvarchar(max)");

            b.HasKey("Id");

            b.HasIndex("BlogId");

            b.ToTable("Comments");

            b.HasData(
                      new
                  {
                    Id = 1,
                    BlogId = 1,
                    Content = "The box this comes in is 5 light-year by 6 foot and weights 17 megaton!!!",
                    Rating = 5,
                    User = "Hương Tiên Phạm"
                  },
                      new
                  {
                    Id = 2,
                    BlogId = 1,
                    Content = "This product works excessively well. It speedily improves my baseball by a lot.",
                    Rating = 3,
                    User = "Xuân Vân Hoàng"
                  },
                      new
                  {
                    Id = 3,
                    BlogId = 2,
                    Content = "one of my hobbies is piano. and when i'm playing piano this works great.",
                    Rating = 1,
                    User = "Huệ Thương Đặng"
                  },
                      new
                  {
                    Id = 4,
                    BlogId = 2,
                    Content = "My neighbor Montserrat has one of these. She works as a circus performer and she says it looks shriveled.",
                    Rating = 4,
                    User = "Khắc Triệu Mai"
                  },
                      new
                  {
                    Id = 5,
                    BlogId = 2,
                    Content = "I saw one of these in Spratly Islands and I bought one.",
                    Rating = 1,
                    User = "Hùng Ngọc Trần"
                  },
                      new
                  {
                    Id = 6,
                    BlogId = 2,
                    Content = "I tried to grab it but got bonbon all over it.",
                    Rating = 2,
                    User = "Hồng Quý Mai"
                  },
                      new
                  {
                    Id = 7,
                    BlogId = 2,
                    Content = "My neighbor Victoria has one of these. She works as a professor and she says it looks menthol.",
                    Rating = 3,
                    User = "Hiểu Lam Phạm"
                  },
                      new
                  {
                    Id = 8,
                    BlogId = 2,
                    Content = "heard about this on balearic beat radio, decided to give it a try.",
                    Rating = 1,
                    User = "Thảo Hồng Đào"
                  },
                      new
                  {
                    Id = 9,
                    BlogId = 2,
                    Content = "My neighbor Julisa has one of these. She works as a bartender and she says it looks crooked.",
                    Rating = 3,
                    User = "Quốc Mạnh Trần"
                  },
                      new
                  {
                    Id = 10,
                    BlogId = 2,
                    Content = "i use it barely when i'm in my store.",
                    Rating = 4,
                    User = "Trà My Vương"
                  },
                      new
                  {
                    Id = 11,
                    BlogId = 5,
                    Content = "I saw one of these in Bhutan and I bought one.",
                    Rating = 1,
                    User = "Hoa Lý Trịnh"
                  },
                      new
                  {
                    Id = 12,
                    BlogId = 5,
                    Content = "This product works really well. It wildly improves my baseball by a lot.",
                    Rating = 1,
                    User = "Sao Mai Đỗ"
                  },
                      new
                  {
                    Id = 13,
                    BlogId = 5,
                    Content = "I tried to shred it but got watermelon all over it.",
                    Rating = 3,
                    User = "Phi Ðiệp Đinh"
                  },
                      new
                  {
                    Id = 14,
                    BlogId = 6,
                    Content = "This product works outstandingly well. It grudgingly improves my baseball by a lot.",
                    Rating = 1,
                    User = "Nhã Sương Ngô"
                  },
                      new
                  {
                    Id = 15,
                    BlogId = 7,
                    Content = "I saw one of these in Canada and I bought one.",
                    Rating = 3,
                    User = "Xuân Khoa Bùi"
                  },
                      new
                  {
                    Id = 16,
                    BlogId = 7,
                    Content = "It only works when I'm Chad.",
                    Rating = 1,
                    User = "Xuân Phương Phan"
                  },
                      new
                  {
                    Id = 17,
                    BlogId = 7,
                    Content = "this product is ghetto.",
                    Rating = 5,
                    User = "Minh Khai Hoàng"
                  },
                      new
                  {
                    Id = 18,
                    BlogId = 7,
                    Content = "It only works when I'm Rwanda.",
                    Rating = 3,
                    User = "Minh Hiên Nguyễn"
                  },
                      new
                  {
                    Id = 19,
                    BlogId = 7,
                    Content = "one of my hobbies is gaming. and when i'm gaming this works great.",
                    Rating = 5,
                    User = "Bích Loan Đoàn"
                  },
                      new
                  {
                    Id = 20,
                    BlogId = 7,
                    Content = "this product is papery.",
                    Rating = 3,
                    User = "Thái Tâm Trần"
                  },
                      new
                  {
                    Id = 21,
                    BlogId = 7,
                    Content = "My neighbor Forest has one of these. She works as a gardener and she says it looks nude.",
                    Rating = 4,
                    User = "Hải Châu Đặng"
                  },
                      new
                  {
                    Id = 22,
                    BlogId = 8,
                    Content = "My tiger loves to play with it.",
                    Rating = 5,
                    User = "Mộng Hương Tô"
                  },
                      new
                  {
                    Id = 23,
                    BlogId = 8,
                    Content = "It only works when I'm Mauritania.",
                    Rating = 5,
                    User = "Cẩm Nhung Nguyễn"
                  },
                      new
                  {
                    Id = 24,
                    BlogId = 8,
                    Content = "My scarab beetle loves to play with it.",
                    Rating = 3,
                    User = "Hải Bình Hoàng"
                  },
                      new
                  {
                    Id = 25,
                    BlogId = 8,
                    Content = "i use it hardly when i'm in my prison.",
                    Rating = 1,
                    User = "Kim Thủy Phan"
                  },
                      new
                  {
                    Id = 26,
                    BlogId = 8,
                    Content = "this product is mellow.",
                    Rating = 5,
                    User = "Thế Duyệt Phạm"
                  },
                      new
                  {
                    Id = 27,
                    BlogId = 8,
                    Content = "heard about this on melodic death metal radio, decided to give it a try.",
                    Rating = 5,
                    User = "Duy Thành Phan"
                  },
                      new
                  {
                    Id = 28,
                    BlogId = 9,
                    Content = "This product works extremely well. It wetly improves my tennis by a lot.",
                    Rating = 1,
                    User = "Quỳnh Ngân Tô"
                  },
                      new
                  {
                    Id = 29,
                    BlogId = 9,
                    Content = "one of my hobbies is theater. and when i'm acting this works great.",
                    Rating = 5,
                    User = "Quỳnh Thanh Lê"
                  },
                      new
                  {
                    Id = 30,
                    BlogId = 10,
                    Content = "My co-worker Skylar has one of these. He says it looks sweaty.",
                    Rating = 5,
                    User = "Xuân Bình Vũ"
                  },
                      new
                  {
                    Id = 31,
                    BlogId = 10,
                    Content = "works okay.",
                    Rating = 4,
                    User = "Huy Tuấn Phạm"
                  },
                      new
                  {
                    Id = 32,
                    BlogId = 10,
                    Content = "The box this comes in is 5 kilometer by 5 inch and weights 13 kilogram!!!",
                    Rating = 3,
                    User = "Thy Vân Bùi"
                  },
                      new
                  {
                    Id = 33,
                    BlogId = 10,
                    Content = "My co-worker Rey has one of these. He says it looks uneven.",
                    Rating = 2,
                    User = "Minh Hằng Mai"
                  },
                      new
                  {
                    Id = 34,
                    BlogId = 10,
                    Content = "It only works when I'm Samoa.",
                    Rating = 5,
                    User = "Mộc Miên Đặng"
                  },
                      new
                  {
                    Id = 35,
                    BlogId = 10,
                    Content = "this product is amiable.",
                    Rating = 3,
                    User = "Trường Phát Hà"
                  });
          });

      modelBuilder.Entity("ASP_app.Models.Comment", b =>
          {
            b.HasOne("ASP_app.Models.Blog", "Blog")
                      .WithMany("Comments")
                      .HasForeignKey("BlogId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired();

            b.Navigation("Blog");
          });

      modelBuilder.Entity("ASP_app.Models.Blog", b =>
          {
            b.Navigation("Comments");
          });
#pragma warning restore 612, 618
    }
  }
}
