// <auto-generated />
using System;
using ASP_app.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASP_app.Migrations
{
  [DbContext(typeof(AppDbContext))]
  [Migration("20260124155344_Init_Db")]
  partial class Init_Db
  {
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
          .HasAnnotation("ProductVersion", "10.0.2")
          .HasAnnotation("Relational:MaxIdentifierLength", 128);

      SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

      modelBuilder.Entity("ASP_app.Models.Blog", b =>
          {
            b.Property<int>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("int");

            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

            b.Property<string>("Author")
                      .IsRequired()
                      .HasColumnType("nvarchar(max)");

            b.Property<string>("Content")
                      .IsRequired()
                      .HasColumnType("nvarchar(max)");

            b.Property<DateTime>("CreatedAt")
                      .HasColumnType("datetime2");

            b.Property<string>("Title")
                      .IsRequired()
                      .HasColumnType("nvarchar(max)");

            b.HasKey("Id");

            b.ToTable("Blogs");
          });

      modelBuilder.Entity("ASP_app.Models.Comment", b =>
          {
            b.Property<int>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("int");

            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

            b.Property<int>("BlogId")
                      .HasColumnType("int");

            b.Property<string>("Content")
                      .IsRequired()
                      .HasColumnType("nvarchar(max)");

            b.Property<int>("Rating")
                      .HasColumnType("int");

            b.Property<string>("User")
                      .IsRequired()
                      .HasColumnType("nvarchar(max)");

            b.HasKey("Id");

            b.HasIndex("BlogId");

            b.ToTable("Comments");
          });

      modelBuilder.Entity("ASP_app.Models.Comment", b =>
          {
            b.HasOne("ASP_app.Models.Blog", "Blog")
                      .WithMany("Comments")
                      .HasForeignKey("BlogId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired();

            b.Navigation("Blog");
          });

      modelBuilder.Entity("ASP_app.Models.Blog", b =>
          {
            b.Navigation("Comments");
          });
#pragma warning restore 612, 618
    }
  }
}
